name: 'SWM: Deploy to Azure'

on:
  pull_request:
    branches:
    - main

jobs:
  call_build_test:
    uses: JGeun/swm-gha-workshop-advanced/.github/workflow/build-test.yaml@main
    with:
      job_name: 'Build and Test for PR'
      app_location: api
