name: 'SWM: Deploy to Azure'

on:
  pull_request:
    branches:
    - main

jobs:
  call_build_test:
    uses: jgeun/swm-gha-workshop-advanced/.github/workflows/build-test.yaml@main
    with:
      job_name: 'Build and Test for PR'
      app-app_location: api